### PR TITLE
fix(agent): check uppercase & lowercase proxy env

### LINKED ISSUE #22: Check for both upper and lowercase proxy options in env
https://github.com/zkat/make-fetch-happen/blob/latest/index.js#L426-L440

make-fetch-happen looks in the environment for certain proxy settings. I thought originally these were case-insensitive. They're not.

So, add some code to make sure these `process.env` props are checked in both forms.

### PR DESCRIPTION
**Pull request by cilice**
Fixes #22

### CODE REVIEW

File: agent.js [hunk 1]
```diff
@@ -59,15 +59,37 @@ function checkNoProxy (uri) {
   return false
 }
 
+function getProcessEnv (env) {
+  if (!env) { return }
+
+  const processEnv = Object.assign({}, process.env) // process.env calls are slow
```
Comment (zkat) [inline agent.js]: I'm not sure this would save that much all the time: forcing the _entire_ env to get serialized on every `getProcessEnv` and all. I think it's best to just access `process.env` directly, tbh.

File: agent.js [hunk 2]
```diff
@@ -59,15 +59,37 @@ function checkNoProxy (uri) {
...
   const protocol = url.parse(uri).protocol
 
   const proxy = opts.proxy || (
-    protocol === 'https:' && process.env.https_proxy
+    protocol === 'https:' && getProcessEnv('https_proxy')
   ) || (
-    protocol === 'http:' && (
-      process.env.https_proxy || process.env.http_proxy || process.env.proxy
-    )
+    protocol === 'http:' && getProcessEnv(['https_proxy', 'http_proxy', 'proxy'])
```
Comment (zkat) [inline agent.js:93]: so nice~

File: agent.js [hunk 3]
```diff
@@ -59,15 +59,37 @@ function checkNoProxy (uri) {
   return false
 }
 
+function getProcessEnv (env) {
```
Comment (zkat) [inline agent.js]: Can you export this function and write a small unit test for it? I think this is the kind of size that it's much easier to unit test :)

**Review by zkat — CHANGES_REQUESTED** [review]
Looks good! I like this style of doing the fallbacks a lot! A couple of minor nits, and I'm thinking it's a good idea to be picky about wanting tests for new code, specially now that it's factored so much nicer.

**Review by zkat — APPROVED** [review]
💯 🐑
